    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Juego.Jugador;
import Juego.Otello;
import Juego.Tiempo;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Nebura
 */
public class FrmOTELO extends javax.swing.JFrame implements Runnable {

    protected Tiempo time;
    private boolean estado;
    private String player1, player2, colorficha1, colorficha2;
    private Otello out;
    Jugador jugador1, jugador2;

    public void registro() {
        while (this.estado) {
            try {
                this.player1 = lblJugador1.getText();
                this.player2 = lblJugador2.getText();
                this.colorficha1 = lblColor1.getText();
                this.colorficha2 = lblColor2.getText();
                if (this.player1 != "Jugador 1" && this.player2 != "Jugador 2"
                        && (this.colorficha1 == "Negro" && (this.colorficha2 == "Blanco")
                        || (this.colorficha1 == "Blanco" && this.colorficha2 == "Negro"))) {
                    jugador1 = new Jugador(this.player1, this.colorficha1, lblPuntos1);
                    jugador2 = new Jugador(this.player2, this.colorficha2, lblPuntos2);
                    Otello.añadir(jugador1, jugador2);
                    this.jMenuItem2.setEnabled(false);
                    try {
                        time.start();
                    } catch (Exception e) {
                    }
                    this.estado = false;
                }
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
            }
        }
    }

    /**
     * Creates new form prueba
     */
    public FrmOTELO() {
        initComponents();
        out = new Otello();
        crearTablero();
        mostrar();
        this.estado = true;
        time = new Tiempo(BtnMin, BtnSec);
        this.getContentPane().setBackground(Color.decode("#669B28"));
        this.setExtendedState(MAXIMIZED_BOTH);
        Thread hilo = new Thread(this);
        hilo.start();
    }

    private void refrescar() {
        while (true) {
            for (int f = 0; f < 12; f++) {
                for (int c = 0; c < 12; c++) {
                    if (Otello.getTab().getTablero()[f][c].isCambio()) {
                        Otello.getTab().getTablero()[f][c].getBtn().setEnabled(false);
                        Otello.getTab().getTablero()[f][c].getBtn().setBounds(f * 55, c * 55, 55, 55);
                        actualizar(f, c);
                    }
                }
            }
        }
    }

    private void actualizar(int f, int c) {
        for (int k = 0; k < 23; k++) {
            Otello.getTab().getTablero()[f][c].getBtn().setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/" + Otello.getTab().getTablero()[f][c].getColor() + k + ".png")));
            try {
                Thread.sleep(15);
            } catch (InterruptedException ex) {
                Logger.getLogger(FrmOTELO.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Otello.getTab().getTablero()[f][c].setCambio(false);
    }

    /**
     * this method create a visual board
     */
    private void crearTablero() {
        for (int i = 0; i < 12; i++) {
            for (int j = 0; j < 12; j++) {
                JLabel lbltab = new JLabel();
                lbltab.setBounds(i * 55, j * 55, 55, 55);
                lbltab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/Tablero.png")));
                this.getContentPane().add(lbltab);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnMin = new javax.swing.JButton();
        BtnSec = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        lblPuntos1 = new javax.swing.JLabel();
        lblPuntos2 = new javax.swing.JLabel();
        lblJugadores = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();
        lblColor2 = new javax.swing.JLabel();
        lblcolor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Othello");
        setBackground(new java.awt.Color(169, 7, 227));

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Tiempo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 1, 36))); // NOI18N

        BtnMin.setBackground(new java.awt.Color(0, 153, 153));
        BtnMin.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        BtnMin.setText("00");
        BtnMin.setPreferredSize(new java.awt.Dimension(50, 50));

        BtnSec.setBackground(new java.awt.Color(0, 153, 153));
        BtnSec.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        BtnSec.setText("00");
        BtnSec.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel1.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BtnSec, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BtnSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Menu:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 1, 36))); // NOI18N

        lblJugador1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblJugador1.setText("Jugador 1");

        lblJugador2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblJugador2.setText("Jugador 2");

        lblTurno.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblTurno.setText("Turno de jugador:");

        lblPuntos1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblPuntos1.setText("0");

        lblPuntos2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblPuntos2.setText("0");

        lblJugadores.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblJugadores.setText("Jugador ?");

        lblColor1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblColor1.setText("Color");

        lblColor2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblColor2.setText("Color");

        lblcolor.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblcolor.setText("¿color?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblJugador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblColor2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPuntos2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblJugador1)
                                .addGap(18, 18, 18)
                                .addComponent(lblColor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPuntos1))))
                    .addComponent(lblTurno)
                    .addComponent(lblJugadores)
                    .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJugador1)
                        .addComponent(lblColor1))
                    .addComponent(lblPuntos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntos2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblJugador2)
                        .addComponent(lblColor2)))
                .addGap(210, 210, 210)
                .addComponent(lblTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblcolor.getAccessibleContext().setAccessibleName("");

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Reglas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Registro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(831, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmReglas reglas = new FrmReglas(null, true);
        reglas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Registro registro = new Registro(null, true);
        registro.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * this method create a set image to the button files
     */
    private void mostrar() {
        for (int i = 0; i < 12; i++) {
            for (int j = 0; j < 12; j++) {
                Otello.getTab().getTablero()[i][j].getBtn().setBounds(i * 55, j * 55, 55, 55);
                if (Otello.getTab().getTablero()[i][j].getColor().equals("Neutral")) {
                    Otello.getTab().getTablero()[i][j].getBtn().setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/Neutral.png")));
                }
                this.getContentPane().add(Otello.getTab().getTablero()[i][j].getBtn(), 1);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOTELO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOTELO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOTELO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOTELO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOTELO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMin;
    private javax.swing.JButton BtnSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblColor1;
    public static javax.swing.JLabel lblColor2;
    public static javax.swing.JLabel lblJugador1;
    public static javax.swing.JLabel lblJugador2;
    public static javax.swing.JLabel lblJugadores;
    private javax.swing.JLabel lblPuntos1;
    private javax.swing.JLabel lblPuntos2;
    private javax.swing.JLabel lblTurno;
    public static javax.swing.JLabel lblcolor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        registro();
        refrescar();
    }
}
