/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.FrmOTELO.lblColor1;
import static GUI.FrmOTELO.lblColor2;
import static GUI.FrmOTELO.lblJugador1;
import static GUI.FrmOTELO.lblJugador2;
import Juego.Jugador;
import Juego.Otello;

/**
 *
 * @author kille
 */
public class Registro extends javax.swing.JDialog implements Runnable {

    protected static boolean estado = true;

    public static void setEstado(boolean reiniciar) {
        estado = reiniciar;
    }
    
    public void registro() {
        while (Registro.estado) {
            try {

                if (FrmOTELO.lblJugador1.getText() != "Jugador 1" && FrmOTELO.lblJugador2.getText() != "Jugador 2"
                        && (FrmOTELO.lblColor1.getText() == "Negro" && (FrmOTELO.lblColor2.getText() == "Blanco")
                        || (FrmOTELO.lblColor1.getText() == "Blanco" && FrmOTELO.lblColor2.getText() == "Negro"))) {
                    this.dispose();

                    estado = false;
                }
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
            }
        }
    }

    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Thread h1 = new Thread(this);
        h1.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnNegro1 = new javax.swing.JButton();
        BtnNegro2 = new javax.swing.JButton();
        BtnBlanco1 = new javax.swing.JButton();
        BtnBlanco2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setResizable(false);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnNegro1.setText("Negro");
        BtnNegro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNegro1ActionPerformed(evt);
            }
        });

        BtnNegro2.setText("Negro");
        BtnNegro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNegro2ActionPerformed(evt);
            }
        });

        BtnBlanco1.setText("Blanco");
        BtnBlanco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBlanco1ActionPerformed(evt);
            }
        });

        BtnBlanco2.setText("Blanco");
        BtnBlanco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBlanco2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNegro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBlanco1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNegro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBlanco2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(BtnNegro1)
                    .addComponent(BtnBlanco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(BtnNegro2)
                    .addComponent(BtnBlanco2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmOTELO.lblJugador1.setText(txtJugador1.getText());
        this.txtJugador1.setEnabled(false);
        this.jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmOTELO.lblJugador2.setText(txtJugador2.getText());
        this.txtJugador2.setEnabled(false);
        this.jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnNegro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNegro2ActionPerformed
        FrmOTELO.lblColor2.setText(BtnNegro2.getText());
        this.BtnBlanco2.setEnabled(false);
        this.BtnNegro1.setEnabled(false);
        this.BtnNegro2.setEnabled(false);
    }//GEN-LAST:event_BtnNegro2ActionPerformed

    private void BtnNegro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNegro1ActionPerformed
        FrmOTELO.lblColor1.setText(BtnNegro1.getText());
        this.BtnBlanco1.setEnabled(false);
        this.BtnNegro1.setEnabled(false);
        this.BtnNegro2.setEnabled(false);
    }//GEN-LAST:event_BtnNegro1ActionPerformed

    private void BtnBlanco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBlanco1ActionPerformed
        FrmOTELO.lblColor1.setText(BtnBlanco1.getText());
        this.BtnBlanco1.setEnabled(false);
        this.BtnNegro1.setEnabled(false);
        this.BtnBlanco2.setEnabled(false);
    }//GEN-LAST:event_BtnBlanco1ActionPerformed

    private void BtnBlanco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBlanco2ActionPerformed
        FrmOTELO.lblColor2.setText(BtnBlanco2.getText());
        this.BtnBlanco2.setEnabled(false);
        this.BtnNegro2.setEnabled(false);
        this.BtnBlanco1.setEnabled(false);
    }//GEN-LAST:event_BtnBlanco2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void run() {
        registro();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBlanco1;
    private javax.swing.JButton BtnBlanco2;
    private javax.swing.JButton BtnNegro1;
    private javax.swing.JButton BtnNegro2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
